
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/api-hotel
    username: root
    password: Localhost123...
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

    livereload:
      enabled: true
      additional-paths: src/main/java


server:
  error:
    include-stacktrace: never
#api:
#  security:
#    secret: ${JWT_SECRET:123456}
